name: Build And Upload Extension Zip Via Artifact

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build
      - uses: actions/upload-artifact@v7
        with:
          path: dist/*
